version: '3.7'
services:
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - nodeapp-network
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  node:
    restart: always
    build: .
    depends_on:
      - mongo
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    networks:
      - nodeapp-network
    links:
      - mongo

networks:
  nodeapp-network:
    driver: bridge

volumes:
  data:

